[[redirects]]
  from = "/container/*"
  to = "/container/index.html"
  status = 200

[[redirects]]
  from = "/marketing/*"
  to = "/marketing/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/container/index.html"
  status = 200