
[build]
  base = "packages/container/"
  command = "echo 'Build not required'"
  publish = "packages/container/dist/"

[[redirects]]
  from = "/*"
  to = "/packages/container/:splat"
  status = 200

[[redirects]]
  from = "/packages/container/*"
  to = "/packages/container/:splat"
  status = 200

[[redirects]]
  from = "/packages/marketing/*"
  to = "/packages/marketing/:splat"
  status = 200