[build]
  command = "echo 'Build not required'"
  functions = "functions/"

[[redirects]]
  from = "/*"
  to = "/packages/container/:splat"
  status = 200

[[redirects]]
  from = "/packages/container/*"
  to = "/packages/container/:splat"
  status = 200

[[redirects]]
  from = "/packages/marketing/*"
  to = "/packages/marketing/:splat"
  status = 200