name: deploy-marketing

on:
  push:
    branches:
      - main
    paths:
      - 'packages/marketing/**'

defaults:
  run:
    working-directory: ./packages/marketing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install dependencies and build marketing
        run: |
          npm install
          npm run build
        env:
          PROD_DOMAIN: ${{ secrets.MARKETING_SITE_ID }}

      - name: Copy netlify.toml
        run: cp netlify.toml ./packages/marketing/dist

      - name: List Files in Root Directory
        run: |
          echo "Root directory: $(basename $(pwd))"
          ls -R
      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=./packages/marketing/dist --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_SITE_ID: ${{ secrets.MARKETING_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


