name: deploy-marketing

on:
  push:
    branches:
      - main
    paths:
      - 'packages/marketing/**'

defaults:
  run:
    working-directory: ./packages/marketing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies and build marketing
        run: |
          npm install
          npm run build
      - name: List Files in Root Directory
        run: ls -R
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=dist --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_SITE_ID: 307ce18d-5cec-4110-aa9a-9f63e55838b9
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


